name: External events
on:
  repository_dispatch:
#must be pushed to default branch ( main branch ) otherwise it wont work
jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{github.event.client_payload.env}}
