
name: Matrix
on: [push]

#------- ORIGINAL --------#
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 17 }

jobs:
    node-matrix:
        continue-on-error: false # this will make the workflow fail if any of the matrix runs fail, instead of waiting for all the runs to complete and then marking the workflow as failed if any of the runs have failed
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14, 15, 16]
                include:
                    - os: ubuntu-latest 
                      is-ubuntu: true # this will just add a  new key to all ubuntu runs  : is-ubuntu == true ( this will merge)
                    - os: macos-latest
                      node-version: 20 # this will add a new run with macos-latest and node version 15 ' wont merge like the other one cause we never had an item that runs on mac os  so it creates one . 
                    - experimental: false   # wont override and wont add a new run  but it will be merged with all  the original matrix combinations
                    - os: ubuntu-latest
                      node-version: 16 
                      experimental: true #this will just change experimental value for the ubuntu os that runs node version 16 to true and it will be merged with the original matrix combination that has ubuntu-latest and node version 16
                    - os: ubuntu-latest
                      node-version: 17 
                exclude:
                    - os: ubuntu-latest 
                      node-version: 14 # this will exclude the run that has ubuntu-latest and node version 14 from the matrix and it wont run at all

            fail-fast: true # this will make the workflow fail immediately if any of the matrix runs fail, instead of waiting for all the runs to complete and then marking the workflow as failed if any of the runs have failed
            #max-parallel: 3 # this will limit the number of parallel jobs to 2, even if there are more combinations in the matrix, only 2 jobs will run at the same time and the others will wait for one of the running jobs to finish before starting
        runs-on: ${{ matrix.os }}
        steps:
            - if: matrix.experimental == true
              run: exit 1 # this will make the job fail if the experimental key is set to true in the matrix combination
              
            - run: node -v
            - run: echo '${{toJson(matrix) }}'
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v
