name: status check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: sleep 90 # this will make the step run for 90 seconds
              timeout-minutes: 1 # this will set a timeout of 1 minute for this step, if the step takes longer than 1 minute to complete, it will be automatically cancelled and marked as failed

            - name: Step 2
              id: step-2
              continue-on-error: true # this will allow the workflow to continue even if this step fails
              run: exit 1
              
            - name: Runs on step 2Failure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo 'Step 2 has failed'

            - name: Runs on Failure
              if: failure() 
              run: echo 'failed'
            
            - name: run on success
            # this is not needed  cause its a default behaviour
              if: success() # this step will run only if all the previous steps in the job have succeeded
              run: echo "This step runs only if all the previous steps have succeeded"

            - name: run always
              if: always() # this step will run regardless of the outcome of the previous steps in the job and works if workflow is cancaled
              run: echo "This step runs regardless of the outcome of the previous steps in the job"

            - name: run when cancelled
              if: cancelled() # this step will run only if the workflow run is cancelled
              run: echo "This step runs only if the workflow run is cancelled"
              
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure() 
        steps:
            - run: echo "job2"